# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-22 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_and_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('travel_start_date', models.DateField(auto_now_add=True)),
                ('travel_end_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trips_created', to='login_and_registration.User')),
                ('travelers', models.ManyToManyField(related_name='Trips_joined', to='login_and_registration.User')),
            ],
        ),
    ]
