# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='Courses_joined', to='login_and_registration.User'),
        ),
    ]
