# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_and_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='login_and_registration.Users')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_group', to='login_and_registration.Users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='login_and_registration.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('expiration', models.DateField()),
                ('amount_used', models.IntegerField()),
                ('max_inventory', models.IntegerField()),
                ('min_inventory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voters', models.ManyToManyField(related_name='votes', to='login_and_registration.Users')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='snack_app.Items'),
        ),
    ]
