# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snack_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buygroup',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta_group', to='login_and_registration.Users'),
        ),
    ]
