# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buygroup',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buygroup',
            name='ta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ta_group', to='login_and_registration.Users'),
        ),
        migrations.AlterField(
            model_name='buygroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to='login_and_registration.Users'),
        ),
    ]
