# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-23 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration', '0001_initial'),
        ('snack_app', '0002_auto_20180423_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buygroup',
            name='ta',
        ),
        migrations.RemoveField(
            model_name='buygroup',
            name='user',
        ),
        migrations.AddField(
            model_name='buygroup',
            name='tas',
            field=models.ManyToManyField(blank=True, null=True, related_name='ta_groups_joined', to='login_and_registration.Users'),
        ),
        migrations.AddField(
            model_name='buygroup',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_groups_joined', to='login_and_registration.Users'),
        ),
    ]
