# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snack_app', '0003_auto_20180424_0631'),
        ('snack_app', '0003_auto_20180423_2309'),
    ]

    operations = [
    ]
